[hikvision-indoor-in]
exten => 10000000005,1,NoOp(Hikvision indoor call)
 same => n,Progress()
 same => n,Set(CALLERID(num)=105)
 same => n,Set(CALLERID(name)=Gate)
 same => n,Dial(PJSIP/101,40)
 same => n,Hangup()
